### ISSUE TITLE
SPIKE: CREATE and KILL Naming Appear to be Related Despite Having Separate Concerns

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astro-cli#40]
We currently have scaffolded out an `airflow create` command which will create deployments on the users cluster. We also have an `airflow kill` command which will destructively stop a local running airflow instance.

This can be confusing for users reviewing list of commands as they appear to be related. I think we should consider renaming `airflow create` to indicate that it will be pushing new containers to your cluster. 

`airflow provision` seems to better describe what is happening.

**Comment by schnie** [comment]
This one will be heavily dependent on a lot of work on Commander and Houston. We should probably hold off on this one for a bit. Auth and deployments to existing clusters (manually deployed with helm) have to be in place before we can tackle this.

**Comment by schnie** [comment]
Realized that this issue is more about naming, than the actual functionality so wondering if we'll be adding more `create` style commands, in addition to creating a cluster. It could make sense to have `create` as it's own subcommand: `astro airflow create deployment ...`, `astro airflow create user ...`, `astro airflow create something-else`.

I could also see us adding `astro airflow delete deployment ...` and maybe some other verbs.

**Comment by andscoop** [comment]
I like the idea of create sub commands. If that means that we will be keeping `create` does it make sense to change `astro airflow kill` to `astro airflow rm` to destructively stop a local cluster? This would remove naming confusion between the `create` and `kill` commands.
