### ISSUE TITLE
Move auth creds to global config

### ISSUE THREAD

**Issue by cwurtz** [astronomerio/astro-cli#96]
The auth JWT should be stored in the global config rather than the project config.

**Comment by schnie** [comment]
I think the reasoning with the project local config was so that you could have projects that correspond to their own clusters. 

Maybe we should treat this more like kubectl and let a user have multiple clusters configured in global config. Then just give CLI abililty to add/switch/delete clusters. Thoughts?

**Comment by cwurtz** [comment]
The problem is with storing sensitive information in the project config.  It'll end up getting committed.  We should try to avoid anything that isn't basically public project level settings from being in that config.

+1 for `astro cluster`
